utils = null
pythonImage = null

node() {
    try {
        timeout(20) {
            init()
            try {
                parallel unittest: {
                    unitTests()
                }, ittest: {
                    integrationTests()
                },
                failFast: true
            } finally {
                publishTestResults()
            }

            pushImageToDockerHub()
        }
        currentBuild.result = 'SUCCESS'
    } catch(e) {
        currentBuild.result = 'FAILURE'
    }
}

// Stages begin here

def init() {
    stage('init') {
        checkout scm
        utils = load "./ci-cd/pipelines/utils.groovy"

        def commitInfo = (sh (label: 'Get commit info', returnStdout: true, script: 'git log -n 1 --format="%H;%T;%an;%ae;%s"')).trim().split(';')
        utils.commitHash = commitInfo[0]

        sh "printenv"
        echo "commitHash: ${utils.commitHash}"

        echo "Building python runtime image..."
        dir("ci-cd/images/python-runtime") {
            def tag = (env.BRANCH_NAME).replaceAll('/','-')
            pythonImage = docker.build("python-runtime:${tag}")
        }
    }
}

def unitTests() {
    utils.stageWithGHStatusCheck('unit tests') {
        pythonImage.inside {
            withEnv(["PYTHONPATH=${pwd()}"]) {
                sh 'pytest --junit-xml="pytest_results.xml"'
            }
        }
    }
}

def integrationTests() {
    utils.stageWithGHStatusCheck('integration tests') {
        echo "To be implemented!"
    }
}

def publishTestResults() {
    utils.stageWithGHStatusCheck('publish unit test results') {
        junit 'pytest_results.xml'
    }
}

def pushImageToDockerHub() {
    utils.stageWithGHStatusCheck('push image') {
        def branch = (env.BRANCH_NAME).replaceAll('/','-')
        def appImageName = "sunnyredhu/ci-task:${branch}-${commitHash}"
        echo "Building image: ${appImageName}..."
        def appImage = docker.build(appImageName)
        echo "Done.\nPushing image: ${appImageName}..."
        docker.withRegistry('', "sunny-dockerhub-credentials") {
            appImage.push()
        }
        echo "Done."
    }
}

// Stages end here