utils = null
pythonImage = null

node() {
    try {
        timeout(30) {
            init()
            try {
                parallel unittest: {
                    unitTests()
                }, ittest: {
                    integrationTests()
                },
                failFast: true
            } finally {
                publishTestResults()
            }

            deploy()
        }

        currentBuild.result = 'SUCCESS'
    } catch(e) {
        currentBuild.result = 'FAILURE'
    }
}

// Stages begin here

def init() {
    stage('init') {
        checkout scm
        utils = load "./ci-cd/pipelines/utils.groovy"

        def commitInfo = (sh (label: 'Get commit info', returnStdout: true, script: 'git log -n 1 --format="%H;%T;%an;%ae;%s"')).trim().split(';')
        utils.commitHash = commitInfo[0]

        sh "printenv"
        echo "commitHash: ${utils.commitHash}"

        echo "Building python runtime image..."
        dir("ci-cd/images/python-runtime") {
            def tag = (env.BRANCH_NAME).replaceAll('/','-')
            pythonImage = docker.build("python-runtime:${tag}")
        }
    }
}

def unitTests() {
    utils.stageWithGHStatusCheck('unit tests') {
        pythonImage.inside {
            withEnv(["PYTHONPATH=${pwd()}"]) {
                sh 'pytest --junit-xml="pytest_results.xml"'
            }
        }
    }
}

def integrationTests() {
    utils.stageWithGHStatusCheck('integration tests') {
        echo "To be implemented!"
    }
}

def publishTestResults() {
    utils.stageWithGHStatusCheck('publish unit test results') {
        junit 'pytest_results.xml'
    }
}

def deploy() {
    stage('deploy') {
        build (
            job: 'ci-task-deployment',
            parameters: [
                string(name: 'BRANCH_TO_DEPLOY', value: commitHash),
                string(name: 'BRANCH_NAME', value: env.BRANCH_NAME)
            ]
        )
    }
}

// Stages end here